AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API interfaces and Lambda Function for Cloudtrail interfaces.

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./swagger.yaml
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref LambdaFunction

  LambdaFunctionIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowLambdaServiceToAssumeRole"
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "lambda.amazonaws.com"
          Policies:
            -
              PolicyName: "InlinePolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action:
                      - "logs:CreateLogGroup"
                      - "logs:CreateLogStream"
                      - "logs:PutLogEvents"
                    Resource: "arn:aws:logs:*:*:*"
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:GetObject"
                    Resource: "arn:aws:s3:::*"
                  -
                    Effect: "Allow"
                    Action:
                      - "cloudtrail:DescribeTrails"
                      - "cloudtrail:GetTrailStatus"
                      - "cloudtrail:LookupEvents"
                      - "cloudtrail:CreateTrail"
                      - "cloudtrail:StartLogging"
                      - "cloudtrail:StopLogging"
                      - "cloudtrail:DeleteTrail"
                      - "s3:ListAllMyBuckets"
                      - "s3:CreateBucket"
                      - "s3:GetBucketPolicy"
                      - "s3:PutBucketPolicy"
                    Resource: "*"

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./src
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Timeout: 300
      Environment:
        Variables:
          TRAIL_NAME: "Default"
          BUCKET_NAME_POSTFIX: ".cloudtrail"
          BUCKET_POLICY_NAME: "bucket_cloudtrail_policy"
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'

  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
